Link script work

diff --git a/bin/link_paths b/bin/link_paths
--- a/bin/link_paths
+++ b/bin/link_paths
@@ -18,8 +18,22 @@ else
         sudo mkdir ${ANSIBLE_BASE}
     fi
 
+    if [ -e ${ANSIBLE_BASE}/hosts ]; then
+        echo "${ANSIBLE_BASE}/hosts exists already..."
+        if [ -h ${ANSIBLE_BASE}/hosts ]; then
+            echo "... and is already a symlink. I don't know what to do - terminating with no links made."
+            exit 1
+        else
+            read -p "... and appears to be a flat file. This is probably the default (empty) config. Delete and replace? (Y|n) " choice
+            case "$choice" in
+                y|Y ) echo "Deleteing and replacing"; sudo rm ${ANSIBLE_BASE}/hosts;;
+                * ) echo "Aborting"; exit 2;;
+            esac
+        fi
+    fi
+
     echo Creating symlinks within ${ANSIBLE_BASE} using sudo
-    sudo ln -s ${PWD}/hosts ${ANSIBLE_BASE}/hosts
-    sudo ln -s ${PWD}/group_vars/ ${ANSIBLE_BASE}/group_vars
-    sudo ln -s ${PWD}/host_vars/ ${ANSIBLE_BASE}/host_vars
+    ([ ! -e ${ANSIBLE_BASE}/hosts ] && echo "hosts file exists, skipping") || sudo ln -s ${PWD}/hosts ${ANSIBLE_BASE}/hosts
+    ([ ! -e ${ANSIBLE_BASE}/group_vars ] && echo "group_vars exists, skipping") || sudo ln -s ${PWD}/group_vars/ ${ANSIBLE_BASE}/group_vars
+    ([ ! -e ${ANSIBLE_BASE}/host_vars ] && echo "host_vars exists, skipping") || sudo ln -s ${PWD}/host_vars/ ${ANSIBLE_BASE}/host_vars
 fi
